FROM node:16.18.0-slim

# Create app directory
WORKDIR /home/node/app/

# Install app dependencies
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm i

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 5000
CMD [ "pnpm", "dev" ]