services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/app
    container_name: app
    ports:
      - 5000:5000
  #   depends_on:
  #     - db

  # db:
  #   image: mongo:6.0.2
  #   profiles:
  #     - dev
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./.docker/dbdata:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
